server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazyms
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
